# Generated by Django 5.0 on 2023-12-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=255)),
                ("exchange_name", models.CharField(blank=True, max_length=32)),
                ("exchange_api_code", models.CharField(blank=True, max_length=32)),
                ("security_code", models.CharField(blank=True, max_length=32)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(null=True)),
                ("data", models.JSONField(default=dict)),
            ],
        ),
    ]
