# Generated by Django 5.0 on 2024-01-05 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("strategy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompositeOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_type", models.CharField(max_length=32)),
                ("quantity", models.FloatField(default=0)),
                ("filled_quantity", models.FloatField(default=0)),
                ("average_fill_price", models.FloatField(default=0)),
                ("total_cost", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(default=dict)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.decision",
                    ),
                ),
                (
                    "strategy_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.strategysession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_type", models.CharField(max_length=32)),
                ("exchange_order_id", models.CharField(blank=True, max_length=255)),
                ("security_code", models.CharField(blank=True, max_length=32)),
                ("side", models.CharField(blank=True, max_length=32)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date_at", models.DateTimeField(null=True)),
                ("quantity", models.FloatField(default=0)),
                ("filled_quantity", models.FloatField(default=0)),
                ("average_fill_price", models.FloatField(default=0)),
                ("total_cost", models.FloatField(default=0)),
                ("exchange_name", models.CharField(blank=True, max_length=32)),
                ("exchange_api_code", models.CharField(blank=True, max_length=32)),
                ("data", models.JSONField(default=dict)),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.decision",
                    ),
                ),
                (
                    "parent_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.compositeorder",
                    ),
                ),
                (
                    "strategy_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="strategy.strategysession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("date_at", models.DateTimeField()),
                ("quantity", models.FloatField(default=0)),
                ("price", models.FloatField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="order.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderEventEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(blank=True, max_length=32)),
                ("date_at", models.DateTimeField()),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.order",
                    ),
                ),
                (
                    "parent_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.compositeorder",
                    ),
                ),
                (
                    "trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.trade",
                    ),
                ),
            ],
        ),
    ]
