# Generated by Django 5.0 on 2024-01-06 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_order_order_price_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderevententry",
            old_name="parent_order",
            new_name="composite_order",
        ),
    ]
