# Generated by Django 5.0 on 2024-01-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_rename_parent_order_orderevententry_composite_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="exchange_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
