# Generated by Django 5.0 on 2024-01-12 12:37

import open_investing.order.const.order
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_order_exchange_order_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="compositeorder",
            name="life_stage",
            field=models.CharField(
                blank=True,
                default=open_investing.order.const.order.OrderLifeStage["Undefined"],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="life_stage",
            field=models.CharField(
                blank=True,
                default=open_investing.order.const.order.OrderLifeStage["Undefined"],
                max_length=32,
            ),
        ),
    ]
