# Generated by Django 5.0.1 on 2024-01-13 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_remove_order_status_compositeorder_life_stage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderOffsetRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offset_quantity", models.PositiveIntegerField(default=0)),
                ("filled_quantity", models.PositiveIntegerField(default=0)),
                ("fully_offsetted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offsetted_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_offsetting_me",
                        to="order.order",
                    ),
                ),
                (
                    "offsetting_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_offsetted_by_me",
                        to="order.order",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="offsetted_by_me",
            field=models.ManyToManyField(
                related_name="offsetting_me",
                through="order.OrderOffsetRelation",
                to="order.order",
            ),
        ),
    ]
