# Generated by Django 5.0.1 on 2024-01-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_orderoffsetrelation_order_offsetted_by_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
