# Generated by Django 5.0.1 on 2024-01-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_order_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="exchange_order_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
