# Generated by Django 5.0.1 on 2024-01-18 07:30

import open_investing.order.const.order
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_alter_order_exchange_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="exchange_order_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="life_stage",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=open_investing.order.const.order.OrderLifeStage["Undefined"],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="order",
            name="security_code",
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
