# Generated by Django 5.0.1 on 2024-01-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_alter_compositeorder_average_fill_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="average_fill_price",
            new_name="average_fill_price_amount",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="price",
            new_name="price_amount",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="total_cost",
            new_name="total_cost_amount",
        ),
        migrations.RenameField(
            model_name="trade",
            old_name="price",
            new_name="price_amount",
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(default="KRW", max_length=3),
        ),
        migrations.AddField(
            model_name="trade",
            name="currency",
            field=models.CharField(default="KRW", max_length=3),
        ),
    ]
