# Generated by Django 5.0.1 on 2024-01-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "order",
            "0011_rename_average_fill_price_order_average_fill_price_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="life_stage_updated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
