# Generated by Django 5.0.1 on 2024-01-31 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "order",
            "0013_rename_average_fill_price_compositeorder_average_fill_price_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="compositeorder",
            name="currency",
            field=models.CharField(default="KRW", max_length=3),
        ),
    ]
