# Generated by Django 5.0.1 on 2024-01-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_compositeorder_currency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="compositeorder",
            old_name="filled_quantity",
            new_name="filled_quantity_order",
        ),
        migrations.RenameField(
            model_name="compositeorder",
            old_name="quantity",
            new_name="quantity_order",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="filled_quantity",
            new_name="filled_quantity_order",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="quantity",
            new_name="quantity_order",
        ),
        migrations.RenameField(
            model_name="orderoffsetrelation",
            old_name="filled_quantity",
            new_name="filled_quantity_order",
        ),
        migrations.RenameField(
            model_name="orderoffsetrelation",
            old_name="offset_quantity",
            new_name="offset_quantity_order",
        ),
        migrations.AddField(
            model_name="compositeorder",
            name="filled_quantity_exposure",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name="compositeorder",
            name="quantity_exposure",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name="compositeorder",
            name="quantity_multiplier",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=16),
        ),
        migrations.AddField(
            model_name="order",
            name="filled_quantity_exposure",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity_exposure",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity_multiplier",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=16),
        ),
        migrations.AddField(
            model_name="orderoffsetrelation",
            name="quantity_multiplier",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=16),
        ),
    ]
