# Generated by Django 5.0.1 on 2024-01-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0016_rename_quantity_trade_quantity_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compositeorder",
            name="quantity_exposure",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="compositeorder",
            name="quantity_order",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity_exposure",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity_order",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="quantity_order",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
    ]
