# Generated by Django 5.0.1 on 2024-01-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0017_alter_compositeorder_quantity_exposure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compositeorder",
            name="is_offset",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
