# Generated by Django 5.0.1 on 2024-02-05 13:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0019_order_is_offset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderoffsetrelation",
            name="filled_quantity_order",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderoffsetrelation",
            name="offset_quantity_order",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.CreateModel(
            name="CompositeOrderOffsetRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offset_quantity_order",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "filled_quantity_order",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "quantity_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=16
                    ),
                ),
                ("fully_offsetted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "offsetted_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_offsetting_me",
                        to="order.compositeorder",
                    ),
                ),
                (
                    "offsetting_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_offsetted_by_me",
                        to="order.compositeorder",
                    ),
                ),
            ],
        ),
    ]
