# Generated by Django 5.0.1 on 2024-02-20 06:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0020_alter_orderoffsetrelation_filled_quantity_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="leader_follower_ratio",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=16
            ),
        ),
    ]
