# Generated by Django 5.0.1 on 2024-02-20 13:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0022_alter_order_leader_follower_ratio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compositeorderoffsetrelation",
            name="filled_quantity_order",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=16
            ),
        ),
        migrations.AlterField(
            model_name="compositeorderoffsetrelation",
            name="offset_quantity_order",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=16
            ),
        ),
    ]
