# Generated by Django 5.0.1 on 2024-02-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0024_rename_leader_follower_ratio_order_leader_quantity_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="leader_follower_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
    ]
