# Generated by Django 5.0.1 on 2024-02-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0025_order_leader_follower_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="compositeorder",
            name="life_stage_updated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
