# Generated by Django 4.2.6 on 2023-11-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityoption",
            name="date_time",
            field=models.DateTimeField(),
        ),
    ]
