# Generated by Django 5.0 on 2023-12-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0002_rename_s_price_securityoption_strike_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="NearbyFuture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expire_date", models.DateField(blank=True, null=True)),
                ("exchange_api_code", models.CharField(blank=True, max_length=32)),
                ("exchange_name", models.CharField(blank=True, max_length=32)),
                ("timeframe", models.DurationField()),
                ("date_at", models.DateTimeField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="securityfuture",
            name="securityfuture_unique_security_code_date_time",
        ),
        migrations.RemoveConstraint(
            model_name="securityoption",
            name="securityoption_unique_security_code_date_time",
        ),
        migrations.RenameField(
            model_name="securityfuture",
            old_name="create_time",
            new_name="create_at",
        ),
        migrations.RenameField(
            model_name="securityfuture",
            old_name="date_time",
            new_name="date_at",
        ),
        migrations.RenameField(
            model_name="securityoption",
            old_name="create_time",
            new_name="create_at",
        ),
        migrations.RenameField(
            model_name="securityoption",
            old_name="date_time",
            new_name="date_at",
        ),
        migrations.RemoveField(
            model_name="securityfuture",
            name="tr_code",
        ),
        migrations.AddConstraint(
            model_name="securityfuture",
            constraint=models.UniqueConstraint(
                fields=("security_code", "date_at"),
                name="securityfuture_unique_security_code_date_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="securityoption",
            constraint=models.UniqueConstraint(
                fields=("security_code", "date_at"),
                name="securityoption_unique_security_code_date_time",
            ),
        ),
    ]
