# Generated by Django 4.2.7 on 2023-12-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0002_alter_securityoption_date_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketIndicatorDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
                ),
                ("date", models.DateField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("tr_code", models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.AddConstraint(
            model_name="marketindicatorday",
            constraint=models.UniqueConstraint(
                fields=("name", "date"), name="risk_glass.data_entity.security_unique_name_date"
            ),
        ),
    ]
