# Generated by Django 4.2.7 on 2023-12-03 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0004_securityfuture_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="securityfuture",
            old_name="s_price",
            new_name="price",
        ),
    ]
