# Generated by Django 4.2.6 on 2023-12-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0005_rename_s_price_securityfuture_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="securityfuture",
            name="expire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="securityoption",
            name="expire_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
