# Generated by Django 5.0 on 2023-12-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0005_remove_future_name_remove_future_security_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="future",
            name="expire_date",
        ),
        migrations.RemoveField(
            model_name="nearbyfuture",
            name="expire_date",
        ),
        migrations.RemoveField(
            model_name="option",
            name="expire_date",
        ),
        migrations.AddField(
            model_name="future",
            name="expire_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="nearbyfuture",
            name="expire_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="option",
            name="derivative_type",
            field=models.CharField(db_index=True, default="undefined", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="option",
            name="expire_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="future",
            name="security_code",
            field=models.CharField(db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="nearbyfuture",
            name="date_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="date_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="security_code",
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
