# Generated by Django 5.0 on 2024-01-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0006_remove_future_expire_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nearbyfuture",
            name="derivative_type",
            field=models.CharField(db_index=True, default="MiniFuture", max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="nearbyfuture",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name="nearbyfuture",
            name="security_code",
            field=models.CharField(db_index=True, default="", max_length=8),
            preserve_default=False,
        ),
    ]
