# Generated by Django 5.0 on 2024-01-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0007_nearbyfuture_derivative_type_nearbyfuture_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
