# Generated by Django 5.0 on 2024-01-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0008_option_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("security_code", models.CharField(db_index=True, max_length=8)),
                ("date_at", models.DateTimeField(db_index=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField(default=dict)),
            ],
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.UniqueConstraint(
                fields=("security_code", "date_at"),
                name="securityquote_unique_security_code_date_time",
            ),
        ),
    ]
