# Generated by Django 5.0.1 on 2024-01-13 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0009_quote_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="future",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="nearbyfuture",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="option",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="quote",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
