# Generated by Django 5.0.1 on 2024-01-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0010_rename_create_at_future_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
