# Generated by Django 5.0.1 on 2024-01-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0012_future_derivative_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="future",
            old_name="price",
            new_name="price_amount",
        ),
        migrations.RenameField(
            model_name="nearbyfuture",
            old_name="price",
            new_name="price_amount",
        ),
        migrations.RenameField(
            model_name="option",
            old_name="price",
            new_name="price_amount",
        ),
        migrations.RenameField(
            model_name="option",
            old_name="strike_price",
            new_name="strike_price_amount",
        ),
        migrations.AddField(
            model_name="future",
            name="currency",
            field=models.CharField(default="KRW", max_length=3),
        ),
        migrations.AddField(
            model_name="nearbyfuture",
            name="currency",
            field=models.CharField(default="KRW", max_length=3),
        ),
        migrations.AddField(
            model_name="option",
            name="currency",
            field=models.CharField(default="KRW", max_length=3),
        ),
    ]
