# Generated by Django 5.0.1 on 2024-01-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("security", "0013_rename_price_future_price_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="delta",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0.0, max_digits=16
            ),
        ),
    ]
