# Generated by Django 5.0 on 2023-12-29 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indicator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketindicator",
            old_name="create_time",
            new_name="create_at",
        ),
    ]
