# Generated by Django 5.0.1 on 2024-01-13 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("indicator", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="marketindicator",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
