# Generated by Django 5.0 on 2023-12-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy_id", models.UUIDField()),
                ("strategy_name", models.CharField(max_length=128)),
                ("decision_type", models.CharField(max_length=128)),
                ("decision_params", models.JSONField(default=dict)),
                ("life_stage", models.CharField(max_length=128)),
                ("amount", models.FloatField(default=0)),
                ("filled_amount", models.FloatField(default=0)),
                ("remaining_amount", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
