# Generated by Django 5.0.1 on 2024-01-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategy", "0002_alter_decision_created_at_alter_decision_life_stage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decision",
            name="filled_quantity",
        ),
        migrations.RemoveField(
            model_name="decision",
            name="quantity",
        ),
        migrations.AddField(
            model_name="decision",
            name="filled_quantity_order",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name="decision",
            name="quantity_order",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
