# Generated by Django 5.0.1 on 2024-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("strategy", "0003_remove_decision_filled_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="filled_quantity_exposure",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name="decision",
            name="quantity_exposure",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="quantity_multiplier",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=16),
        ),
        migrations.AlterField(
            model_name="decision",
            name="quantity_order",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
    ]
