:PROPERTIES:
:ID:       2a56b746-63df-43e0-a3c4-dea0d545e194
:END:
#+title: Algorithmic trading


* Hypothesis

I'm not sure this will work.

this might work, because
- market might be efficient
- but people are not rational

* General Strategy

need not perfect information nor perfect algorithm

I'll perform the trading manually and see if I can automate some of my work.

* Goal

** money

beat the stock market by a noticable magine
- when stock market yields 5% return, I want to achieve 5.5% return (10% relatively)

** study

ai, finance, decision making

* Workflow (essential qualities to have)

** hypothesis - predict - see outcome - evaluate loop

** which data to use

*** at what level, data is available in time
- company / sector / country / world
*** integrate human judgement with rule prediction
- probably more efficient to use human judgement

** spell out the decision step

Describe how a decision is made on what basis.

There are many hypothesis / assumptions i'm making when making a decision.
I might not be able to spell out all, but when somethings work or not work, I need to look at the assumptions that I made to evaluate and increment

- emotions
  probably the most powerful factor that governs my decisions but overlooked by myself.
- hypothesis
- prediction rule

** record decisions, I might need to review them


** decision rule, or thinking might be good only in certain situations

For instance, when a stock price rise, it could indicate the company is doing good, or it could mean the stock is getting riskier.
When I make a rule, I assume situations that the rule might be applied favorably
Problem is that I can not see what I don't see.

- test result shows that the decision rule worked or not under the specific situation which I don't fully understand


* Study plan

[[file:~/Dropbox/notes/agendas/investing.org][Study curriculum]]

* algorithm integration principles
:PROPERTIES:
:ID:       eceb0fe6-04c6-478a-9ccb-246258158ad2
:END:

Don't know how much it will work.
Don't lose focus on big picture, algorithm is just for aid.
Be aware that putting energy into it because it captures some idea without clearly specifying the assumptions would result in a wasted time.

On the other hand, when we decide to implement algorithm, desired properties are

[[id:59d6eb18-7046-4e83-aa0a-c02e3173eb88][algorithm develop principles]]


* Decisions as of now

Update decisions as I learn

[[id:ce25f8e0-ccee-4ada-8fae-ed25b42e26e6][decisions]]
